<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Municipio::create(['municipio_nombre' => 'Ahuachapan', 'municipio_codigo' => '101', 'municipio_orden' => 104, 'departamento_id' => 1 ]);
        Municipio::create(['municipio_nombre' => 'San Francisco Menendez', 'municipio_codigo' => '102', 'municipio_orden' => 265, 'departamento_id' => 1 ]);
        Municipio::create(['municipio_nombre' => 'Ataco', 'municipio_codigo' => '103', 'municipio_orden' => 114, 'departamento_id' => 1 ]);
        Municipio::create(['municipio_nombre' => 'Tacuba', 'municipio_codigo' => '104', 'municipio_orden' => 339, 'departamento_id' => 1 ]);
        Municipio::create(['municipio_nombre' => 'Apaneca', 'municipio_codigo' => '105', 'municipio_orden' => 108, 'departamento_id' => 1 ]);
        Municipio::create(['municipio_nombre' => 'San Pedro Puxtla', 'municipio_codigo' => '106', 'municipio_orden' => 301, 'departamento_id' => 1 ]);
        Municipio::create(['municipio_nombre' => 'Guaymango', 'municipio_codigo' => '107', 'municipio_orden' => 173, 'departamento_id' => 1 ]);
        Municipio::create(['municipio_nombre' => 'Jujutla', 'municipio_codigo' => '108', 'municipio_orden' => 191, 'departamento_id' => 1 ]);
        Municipio::create(['municipio_nombre' => 'Atiquizaya', 'municipio_codigo' => '109', 'municipio_orden' => 115, 'departamento_id' => 1 ]);
        Municipio::create(['municipio_nombre' => 'Turin', 'municipio_codigo' => '110', 'municipio_orden' => 368, 'departamento_id' => 1 ]);
        Municipio::create(['municipio_nombre' => 'San Lorenzo', 'municipio_codigo' => '111', 'municipio_orden' => 285, 'departamento_id' => 1 ]);
        Municipio::create(['municipio_nombre' => 'El Refugio', 'municipio_codigo' => '112', 'municipio_orden' => 163, 'departamento_id' => 1 ]);
        Municipio::create(['municipio_nombre' => 'Santa Ana', 'municipio_codigo' => '201', 'municipio_orden' => 312, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'El Congo', 'municipio_codigo' => '202', 'municipio_orden' => 158, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'Coatepeque', 'municipio_codigo' => '203', 'municipio_orden' => 138, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'Texistepeque', 'municipio_codigo' => '204', 'municipio_orden' => 350, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'Chalchuapa', 'municipio_codigo' => '205', 'municipio_orden' => 127, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'Candelaria La Frontera', 'municipio_codigo' => '206', 'municipio_orden' => 124, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'San Sebastian Salitrillo', 'municipio_codigo' => '207', 'municipio_orden' => 309, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'El Porvenir', 'municipio_codigo' => '208', 'municipio_orden' => 162, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'Metapan', 'municipio_codigo' => '209', 'municipio_orden' => 206, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'Santiago La Frontera', 'municipio_codigo' => '210', 'municipio_orden' => 325, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'Masahuat', 'municipio_codigo' => '211', 'municipio_orden' => 200, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'Santa Rosa Guachipilin', 'municipio_codigo' => '212', 'municipio_orden' => 323, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'San Antonio Pajonal', 'municipio_codigo' => '213', 'municipio_orden' => 249, 'departamento_id' => 2 ]);
        Municipio::create(['municipio_nombre' => 'Sonsonate', 'municipio_codigo' => '301', 'municipio_orden' => 335, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Nahuizalco', 'municipio_codigo' => '302', 'municipio_orden' => 212, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Santo Domingo De Guzman', 'municipio_codigo' => '303', 'municipio_orden' => 329, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Nahulingo', 'municipio_codigo' => '304', 'municipio_orden' => 213, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Sonzacate', 'municipio_codigo' => '305', 'municipio_orden' => 336, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'San Antonio Del Monte', 'municipio_codigo' => '306', 'municipio_orden' => 246, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Acajutla', 'municipio_codigo' => '307', 'municipio_orden' => 101, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Izalco', 'municipio_codigo' => '308', 'municipio_orden' => 179, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Armenia', 'municipio_codigo' => '309', 'municipio_orden' => 113, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'San Julian', 'municipio_codigo' => '310', 'municipio_orden' => 284, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Santa Isabel Ishuatan', 'municipio_codigo' => '311', 'municipio_orden' => 318, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Cuisnahuat', 'municipio_codigo' => '312', 'municipio_orden' => 149, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Caluco', 'municipio_codigo' => '313', 'municipio_orden' => 122, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Juayua', 'municipio_codigo' => '314', 'municipio_orden' => 188, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Santa Catarina Masahuat', 'municipio_codigo' => '315', 'municipio_orden' => 313, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Salcoatitan', 'municipio_codigo' => '316', 'municipio_orden' => 242, 'departamento_id' => 3 ]);
        Municipio::create(['municipio_nombre' => 'Chalatenango', 'municipio_codigo' => '401', 'municipio_orden' => 126, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Arcatao', 'municipio_codigo' => '402', 'municipio_orden' => 112, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Isidro Labrador', 'municipio_codigo' => '403', 'municipio_orden' => 272, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Nueva Trinidad', 'municipio_codigo' => '404', 'municipio_orden' => 221, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Jose Las Flores', 'municipio_codigo' => '405', 'municipio_orden' => 277, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Concepción Quezaltepeque', 'municipio_codigo' => '406', 'municipio_orden' => 146, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Nombre De Jesus', 'municipio_codigo' => '407', 'municipio_orden' => 215, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Antonio Los Ranchos', 'municipio_codigo' => '408', 'municipio_orden' => 247, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'El Carrizal', 'municipio_codigo' => '409', 'municipio_orden' => 157, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Antonio De La Cruz', 'municipio_codigo' => '410', 'municipio_orden' => 245, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Las Vueltas', 'municipio_codigo' => '411', 'municipio_orden' => 196, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Potonico', 'municipio_codigo' => '412', 'municipio_orden' => 234, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Luis Carmen', 'municipio_codigo' => '413', 'municipio_orden' => 287, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Azacualpa', 'municipio_codigo' => '414', 'municipio_orden' => 117, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Jose Cancasque', 'municipio_codigo' => '415', 'municipio_orden' => 274, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Miguel De Mercedes', 'municipio_codigo' => '416', 'municipio_orden' => 295, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Francisco Lempa', 'municipio_codigo' => '417', 'municipio_orden' => 264, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Jose Ojos De Agua', 'municipio_codigo' => '418', 'municipio_orden' => 278, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Tejutla', 'municipio_codigo' => '419', 'municipio_orden' => 346, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Nueva Concepcion', 'municipio_codigo' => '420', 'municipio_orden' => 216, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Citala', 'municipio_codigo' => '421', 'municipio_orden' => 134, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'La Palma', 'municipio_codigo' => '422', 'municipio_orden' => 193, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'La Reina', 'municipio_codigo' => '423', 'municipio_orden' => 194, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Ignacio', 'municipio_codigo' => '424', 'municipio_orden' => 268, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Agua Caliente', 'municipio_codigo' => '425', 'municipio_orden' => 102, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Dulce Nombre De Maria', 'municipio_codigo' => '426', 'municipio_orden' => 154, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Fernando', 'municipio_codigo' => '427', 'municipio_orden' => 259, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'El Paraiso', 'municipio_codigo' => '428', 'municipio_orden' => 161, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Francisco Morazan', 'municipio_codigo' => '429', 'municipio_orden' => 266, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'San Rafael', 'municipio_codigo' => '430', 'municipio_orden' => 302, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Santa Rita', 'municipio_codigo' => '431', 'municipio_orden' => 321, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Comalapa', 'municipio_codigo' => '432', 'municipio_orden' => 142, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'La Laguna', 'municipio_codigo' => '433', 'municipio_orden' => 192, 'departamento_id' => 4 ]);
        Municipio::create(['municipio_nombre' => 'Nueva San Salvador', 'municipio_codigo' => '501', 'municipio_orden' => 220, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Jayaque', 'municipio_codigo' => '502', 'municipio_orden' => 180, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Puerto La Libertad', 'municipio_codigo' => '503', 'municipio_orden' => 236, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Comasagua', 'municipio_codigo' => '504', 'municipio_orden' => 143, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Teotepeque', 'municipio_codigo' => '505', 'municipio_orden' => 348, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Huizucar', 'municipio_codigo' => '506', 'municipio_orden' => 175, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Tepecoyo', 'municipio_codigo' => '507', 'municipio_orden' => 349, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Colon', 'municipio_codigo' => '508', 'municipio_orden' => 140, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'San Jose Villanueva', 'municipio_codigo' => '509', 'municipio_orden' => 279, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Tamanique', 'municipio_codigo' => '510', 'municipio_orden' => 341, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Chiltiupan', 'municipio_codigo' => '511', 'municipio_orden' => 130, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Antiguo Cuscatlan', 'municipio_codigo' => '512', 'municipio_orden' => 107, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Nuevo Cuscatlan', 'municipio_codigo' => '513', 'municipio_orden' => 222, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Talnique', 'municipio_codigo' => '514', 'municipio_orden' => 340, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Zaragoza', 'municipio_codigo' => '515', 'municipio_orden' => 380, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Jicalapa', 'municipio_codigo' => '516', 'municipio_orden' => 182, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Sacacoyo', 'municipio_codigo' => '517', 'municipio_orden' => 241, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Quezaltepeque', 'municipio_codigo' => '518', 'municipio_orden' => 238, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'San Pablo Tacachico', 'municipio_codigo' => '519', 'municipio_orden' => 297, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'San Juan Opico', 'municipio_codigo' => '520', 'municipio_orden' => 281, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'San Matias', 'municipio_codigo' => '521', 'municipio_orden' => 293, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'Ciudad Arce', 'municipio_codigo' => '522', 'municipio_orden' => 135, 'departamento_id' => 5 ]);
        Municipio::create(['municipio_nombre' => 'San Salvador', 'municipio_codigo' => '601', 'municipio_orden' => 307, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Mejicanos', 'municipio_codigo' => '602', 'municipio_orden' => 203, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Soyapango', 'municipio_codigo' => '603', 'municipio_orden' => 337, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Ciudad Delgado', 'municipio_codigo' => '604', 'municipio_orden' => 137, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Cuscatancingo', 'municipio_codigo' => '605', 'municipio_orden' => 150, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Ayutuxtepeque', 'municipio_codigo' => '606', 'municipio_orden' => 116, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Tonacatepeque', 'municipio_codigo' => '607', 'municipio_orden' => 366, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Guazapa', 'municipio_codigo' => '608', 'municipio_orden' => 174, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'San Martin', 'municipio_codigo' => '609', 'municipio_orden' => 292, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Apopa', 'municipio_codigo' => '610', 'municipio_orden' => 110, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Nejapa', 'municipio_codigo' => '611', 'municipio_orden' => 214, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Ilopango', 'municipio_codigo' => '612', 'municipio_orden' => 177, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'El Paisnal', 'municipio_codigo' => '613', 'municipio_orden' => 160, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Aguilares', 'municipio_codigo' => '614', 'municipio_orden' => 103, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Santo Tomas', 'municipio_codigo' => '615', 'municipio_orden' => 330, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Panchimalco', 'municipio_codigo' => '616', 'municipio_orden' => 229, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Santiago Texacuangos', 'municipio_codigo' => '617', 'municipio_orden' => 327, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Rosario De Mora', 'municipio_codigo' => '618', 'municipio_orden' => 239, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'San Marcos', 'municipio_codigo' => '619', 'municipio_orden' => 291, 'departamento_id' => 6 ]);
        Municipio::create(['municipio_nombre' => 'Cojutepeque', 'municipio_codigo' => '701', 'municipio_orden' => 139, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'San Pedro Perulapan', 'municipio_codigo' => '702', 'municipio_orden' => 300, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'Tenancingo', 'municipio_codigo' => '703', 'municipio_orden' => 347, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'San Rafael Cedros', 'municipio_codigo' => '704', 'municipio_orden' => 303, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'Candelaria Cuscatlan', 'municipio_codigo' => '705', 'municipio_orden' => 123, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'Monte San Juan', 'municipio_codigo' => '706', 'municipio_orden' => 208, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'El Carmen Cuscatlan', 'municipio_codigo' => '707', 'municipio_orden' => 156, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'San Cristobal', 'municipio_codigo' => '708', 'municipio_orden' => 255, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'Santa Cruz Michapa', 'municipio_codigo' => '709', 'municipio_orden' => 316, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'San Bartolome Perulapia', 'municipio_codigo' => '710', 'municipio_orden' => 251, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'San Ramon', 'municipio_codigo' => '711', 'municipio_orden' => 306, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'El Rosario', 'municipio_codigo' => '712', 'municipio_orden' => 164, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'Santa Cruz Analquito', 'municipio_codigo' => '713', 'municipio_orden' => 315, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'Suchitoto', 'municipio_codigo' => '714', 'municipio_orden' => 338, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'San Jose Guayabal', 'municipio_codigo' => '715', 'municipio_orden' => 276, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'Oratorio De Concepcion', 'municipio_codigo' => '716', 'municipio_orden' => 226, 'departamento_id' => 7 ]);
        Municipio::create(['municipio_nombre' => 'Zacatecoluca', 'municipio_codigo' => '801', 'municipio_orden' => 379, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'Santiago Nonualco', 'municipio_codigo' => '802', 'municipio_orden' => 326, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'San Juan Nonualco', 'municipio_codigo' => '803', 'municipio_orden' => 280, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'San Rafael Obrajuelo', 'municipio_codigo' => '804', 'municipio_orden' => 304, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'San Pedro Nonualco', 'municipio_codigo' => '805', 'municipio_orden' => 299, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'Santa Maria Ostuma', 'municipio_codigo' => '806', 'municipio_orden' => 319, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'San Emigdio', 'municipio_codigo' => '807', 'municipio_orden' => 257, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'Paraiso De Osorio', 'municipio_codigo' => '808', 'municipio_orden' => 230, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'Jerusalen', 'municipio_codigo' => '809', 'municipio_orden' => 181, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'Mercedes La Ceiba', 'municipio_codigo' => '810', 'municipio_orden' => 204, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'Olocuilta', 'municipio_codigo' => '811', 'municipio_orden' => 225, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'San Juan Talpa', 'municipio_codigo' => '812', 'municipio_orden' => 282, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'Cuyultitan', 'municipio_codigo' => '813', 'municipio_orden' => 151, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'San Francisco Chinameca', 'municipio_codigo' => '814', 'municipio_orden' => 261, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'Tapalhuaca', 'municipio_codigo' => '815', 'municipio_orden' => 342, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'San Luis Talpa', 'municipio_codigo' => '816', 'municipio_orden' => 290, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'San Pedro Masahuat', 'municipio_codigo' => '817', 'municipio_orden' => 298, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'San Miguel Tepezontes', 'municipio_codigo' => '818', 'municipio_orden' => 296, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'San Antonio Masahuat', 'municipio_codigo' => '819', 'municipio_orden' => 248, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'San Juan Tepezontes', 'municipio_codigo' => '820', 'municipio_orden' => 283, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'Rosario La Paz', 'municipio_codigo' => '821', 'municipio_orden' => 240, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'San Luis La Herradura', 'municipio_codigo' => '822', 'municipio_orden' => 288, 'departamento_id' => 8 ]);
        Municipio::create(['municipio_nombre' => 'Sensuntepeque', 'municipio_codigo' => '901', 'municipio_orden' => 332, 'departamento_id' => 9 ]);
        Municipio::create(['municipio_nombre' => 'Victoria', 'municipio_codigo' => '902', 'municipio_orden' => 372, 'departamento_id' => 9 ]);
        Municipio::create(['municipio_nombre' => 'Dolores', 'municipio_codigo' => '903', 'municipio_orden' => 153, 'departamento_id' => 9 ]);
        Municipio::create(['municipio_nombre' => 'San Isidro', 'municipio_codigo' => '904', 'municipio_orden' => 270, 'departamento_id' => 9 ]);
        Municipio::create(['municipio_nombre' => 'Guacotecti', 'municipio_codigo' => '905', 'municipio_orden' => 169, 'departamento_id' => 9 ]);
        Municipio::create(['municipio_nombre' => 'Ilobasco', 'municipio_codigo' => '906', 'municipio_orden' => 176, 'departamento_id' => 9 ]);
        Municipio::create(['municipio_nombre' => 'Tejutepeque', 'municipio_codigo' => '907', 'municipio_orden' => 345, 'departamento_id' => 9 ]);
        Municipio::create(['municipio_nombre' => 'Juatiapa', 'municipio_codigo' => '908', 'municipio_orden' => 187, 'departamento_id' => 9 ]);
        Municipio::create(['municipio_nombre' => 'Cinquera', 'municipio_codigo' => '909', 'municipio_orden' => 133, 'departamento_id' => 9 ]);
        Municipio::create(['municipio_nombre' => 'San Vicente', 'municipio_codigo' => '1001', 'municipio_orden' => 311, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'Apastepeque', 'municipio_codigo' => '1002', 'municipio_orden' => 109, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'Guadalupe', 'municipio_codigo' => '1003', 'municipio_orden' => 170, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'Verapaz', 'municipio_codigo' => '1004', 'municipio_orden' => 371, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'Nuevo Tepetitan', 'municipio_codigo' => '1005', 'municipio_orden' => 224, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'Tecoluca', 'municipio_codigo' => '1006', 'municipio_orden' => 344, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'San Cayetano Istepeque', 'municipio_codigo' => '1007', 'municipio_orden' => 254, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'San Sebastian', 'municipio_codigo' => '1008', 'municipio_orden' => 308, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'San Esteban Catarina', 'municipio_codigo' => '1009', 'municipio_orden' => 258, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'San Lorenzo', 'municipio_codigo' => '1010', 'municipio_orden' => 286, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'Santo Domingo', 'municipio_codigo' => '1011', 'municipio_orden' => 328, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'Santa Clara', 'municipio_codigo' => '1012', 'municipio_orden' => 314, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'San Ildefonso', 'municipio_codigo' => '1013', 'municipio_orden' => 269, 'departamento_id' => 10 ]);
        Municipio::create(['municipio_nombre' => 'Usulutan', 'municipio_codigo' => '1101', 'municipio_orden' => 370, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Santa Elena', 'municipio_codigo' => '1102', 'municipio_orden' => 317, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Jiquilisco', 'municipio_codigo' => '1103', 'municipio_orden' => 183, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'San Dionisio', 'municipio_codigo' => '1104', 'municipio_orden' => 256, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Jucuaran', 'municipio_codigo' => '1105', 'municipio_orden' => 190, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Ereguayquin', 'municipio_codigo' => '1106', 'municipio_orden' => 167, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Ozatian', 'municipio_codigo' => '1107', 'municipio_orden' => 228, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Concepcion Batres', 'municipio_codigo' => '1108', 'municipio_orden' => 144, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Santa Maria.', 'municipio_codigo' => '1109', 'municipio_orden' => 320, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Puerto El Triunfo', 'municipio_codigo' => '1110', 'municipio_orden' => 235, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Jucuapa', 'municipio_codigo' => '1111', 'municipio_orden' => 189, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Estanzuelas', 'municipio_codigo' => '1112', 'municipio_orden' => 168, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Villa El Triunfo', 'municipio_codigo' => '1113', 'municipio_orden' => 374, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'San Buenaventura', 'municipio_codigo' => '1114', 'municipio_orden' => 252, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Nueva Granada', 'municipio_codigo' => '1115', 'municipio_orden' => 218, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Santiago De Maria', 'municipio_codigo' => '1116', 'municipio_orden' => 324, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Alegria', 'municipio_codigo' => '1117', 'municipio_orden' => 105, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Tecapan', 'municipio_codigo' => '1118', 'municipio_orden' => 343, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'California', 'municipio_codigo' => '1119', 'municipio_orden' => 121, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Berlin', 'municipio_codigo' => '1120', 'municipio_orden' => 118, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'San Agustin', 'municipio_codigo' => '1121', 'municipio_orden' => 243, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'Mercedes Umaña', 'municipio_codigo' => '1122', 'municipio_orden' => 205, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'San Francisco Javier', 'municipio_codigo' => '1123', 'municipio_orden' => 263, 'departamento_id' => 11 ]);
        Municipio::create(['municipio_nombre' => 'San Miguel', 'municipio_codigo' => '1201', 'municipio_orden' => 294, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Ciudad Barrios', 'municipio_codigo' => '1202', 'municipio_orden' => 136, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Moncagua', 'municipio_codigo' => '1203', 'municipio_orden' => 207, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Uluazapa', 'municipio_codigo' => '1204', 'municipio_orden' => 369, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Chapeltique', 'municipio_codigo' => '1205', 'municipio_orden' => 128, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Chirilangua', 'municipio_codigo' => '1206', 'municipio_orden' => 132, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Quelepa', 'municipio_codigo' => '1207', 'municipio_orden' => 237, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Comacaran', 'municipio_codigo' => '1208', 'municipio_orden' => 141, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Chinameca', 'municipio_codigo' => '1209', 'municipio_orden' => 131, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Nueva Guadalupe', 'municipio_codigo' => '1210', 'municipio_orden' => 219, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'San Rafel Oriente', 'municipio_codigo' => '1211', 'municipio_orden' => 305, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'El Transito', 'municipio_codigo' => '1212', 'municipio_orden' => 166, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Lolotique', 'municipio_codigo' => '1213', 'municipio_orden' => 198, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'San Jorge', 'municipio_codigo' => '1214', 'municipio_orden' => 273, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Sesori', 'municipio_codigo' => '1215', 'municipio_orden' => 333, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'San Luis La Reina', 'municipio_codigo' => '1216', 'municipio_orden' => 289, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Carolina', 'municipio_codigo' => '1217', 'municipio_orden' => 125, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'Nuevo Eden De San Juan', 'municipio_codigo' => '1218', 'municipio_orden' => 223, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'San Gerardo', 'municipio_codigo' => '1219', 'municipio_orden' => 267, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'San Antonio.', 'municipio_codigo' => '1220', 'municipio_orden' => 250, 'departamento_id' => 12 ]);
        Municipio::create(['municipio_nombre' => 'San Francisco Gotera', 'municipio_codigo' => '1301', 'municipio_orden' => 262, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Jocoro', 'municipio_codigo' => '1302', 'municipio_orden' => 186, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'San Carlos', 'municipio_codigo' => '1303', 'municipio_orden' => 253, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Guatajiagua', 'municipio_codigo' => '1304', 'municipio_orden' => 172, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Chilanga', 'municipio_codigo' => '1305', 'municipio_orden' => 129, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Sociedad', 'municipio_codigo' => '1306', 'municipio_orden' => 334, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Yamabal', 'municipio_codigo' => '1307', 'municipio_orden' => 375, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Sensembra', 'municipio_codigo' => '1308', 'municipio_orden' => 331, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Lolotiquillo', 'municipio_codigo' => '1309', 'municipio_orden' => 199, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'El Divisadero', 'municipio_codigo' => '1310', 'municipio_orden' => 159, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Osicala', 'municipio_codigo' => '1311', 'municipio_orden' => 227, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'San Isidro', 'municipio_codigo' => '1312', 'municipio_orden' => 271, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Cacaopera', 'municipio_codigo' => '1313', 'municipio_orden' => 120, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Yoloaiquin', 'municipio_codigo' => '1314', 'municipio_orden' => 377, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Delicias De Concepcion', 'municipio_codigo' => '1315', 'municipio_orden' => 152, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Gualococti', 'municipio_codigo' => '1316', 'municipio_orden' => 171, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'San Simon', 'municipio_codigo' => '1317', 'municipio_orden' => 310, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Corinto', 'municipio_codigo' => '1318', 'municipio_orden' => 148, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Jocoaitique', 'municipio_codigo' => '1319', 'municipio_orden' => 185, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Villa El Rosario', 'municipio_codigo' => '1320', 'municipio_orden' => 373, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Joateca', 'municipio_codigo' => '1321', 'municipio_orden' => 184, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Meanguera', 'municipio_codigo' => '1322', 'municipio_orden' => 201, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Arambala', 'municipio_codigo' => '1323', 'municipio_orden' => 111, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Perquin', 'municipio_codigo' => '1324', 'municipio_orden' => 232, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'San Fernando', 'municipio_codigo' => '1325', 'municipio_orden' => 260, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'Torola', 'municipio_codigo' => '1326', 'municipio_orden' => 367, 'departamento_id' => 13 ]);
        Municipio::create(['municipio_nombre' => 'La Union', 'municipio_codigo' => '1401', 'municipio_orden' => 195, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'San Alejo', 'municipio_codigo' => '1402', 'municipio_orden' => 244, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Yucuaiquin', 'municipio_codigo' => '1403', 'municipio_orden' => 378, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Yayantique', 'municipio_codigo' => '1404', 'municipio_orden' => 376, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Bolivar', 'municipio_codigo' => '1405', 'municipio_orden' => 119, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'El Carmen', 'municipio_codigo' => '1406', 'municipio_orden' => 155, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Conchagua', 'municipio_codigo' => '1407', 'municipio_orden' => 147, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Intipuca', 'municipio_codigo' => '1408', 'municipio_orden' => 178, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'San Jose De La Fuente', 'municipio_codigo' => '1409', 'municipio_orden' => 275, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Meanguera Del Golfo', 'municipio_codigo' => '1410', 'municipio_orden' => 202, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Santa Rosa De Lima', 'municipio_codigo' => '1411', 'municipio_orden' => 322, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Pasaquina', 'municipio_codigo' => '1412', 'municipio_orden' => 231, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Anamoros', 'municipio_codigo' => '1413', 'municipio_orden' => 106, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'El Sauce', 'municipio_codigo' => '1414', 'municipio_orden' => 165, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Nueva Esparta', 'municipio_codigo' => '1415', 'municipio_orden' => 217, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Concepcion De Oriente', 'municipio_codigo' => '1416', 'municipio_orden' => 145, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Poloros', 'municipio_codigo' => '1417', 'municipio_orden' => 233, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'Lislique', 'municipio_codigo' => '1418', 'municipio_orden' => 197, 'departamento_id' => 14 ]);
        Municipio::create(['municipio_nombre' => 'N/A', 'municipio_codigo' => '1501', 'municipio_orden' => 209, 'departamento_id' => 15 ]);
        Municipio::create(['municipio_nombre' => 'N/A', 'municipio_codigo' => '1601', 'municipio_orden' => 210, 'departamento_id' => 16 ]);
        Municipio::create(['municipio_nombre' => 'N/A', 'municipio_codigo' => '1701', 'municipio_orden' => 211, 'departamento_id' => 17 ]);
    }
}
